### ISSUE TITLE
после 1-2 часа работы прилетает undefined и бот падает

### ISSUE THREAD

**Issue by AdvTechnoKing** [Naltox/node-vk-sdk#10]
Короче, не знаю, что я делаю не так, (уже всё перевробовал) но бот работает ровно 1-2 часа и потом спамит тем, что у него приходит пустота:
![image](https://user-images.githubusercontent.com/17812651/42342711-920e9ae2-809f-11e8-98d5-741ec5e2200b.png)

Я уже и return пихал везде и пытался функцию стопать, когда прилетает undefined. Но увы, ничего не получилось, как он присылал undefined так и присылает. Может есть вариант, как можно перезапускать функцию после ошибки?

**Comment by AdvTechnoKing** [comment]
![image](https://user-images.githubusercontent.com/17812651/42449320-e22ebb42-8388-11e8-97ac-d29644a5867f.png)

**Comment by stels-cs** [comment]
Можете привести фрагмент кода который падает?

**Comment by AdvTechnoKing** [comment]
совершенно любой код падает

**Comment by AdvTechnoKing** [comment]
К примеру недавно с кнопками игрался
![image](https://user-images.githubusercontent.com/17812651/42577515-310979a0-852d-11e8-8e0b-d2b455fe1ac1.png)

**Comment by AdvTechnoKing** [comment]
Ну и сами события, если надо
![image](https://user-images.githubusercontent.com/17812651/42577935-1fc5abd6-852e-11e8-9fbb-c29b101a6cea.png)

**Comment by stels-cs** [comment]
Так просто не получится, там есть ситуации  когда надо переполучить ключ для longpoll, придется подождать пока  @Naltox поправит

**Comment by AdvTechnoKing** [comment]
Ну ок, до сентября успеет хоть?

**Comment by AdvTechnoKing** [comment]
Про меня там не забыли?

**Comment by yuickhahirasawa** [comment]
@AdvTechnoKing в моём форке этот баг исправлен.

**Comment by AdvTechnoKing** [comment]
Да уже не надо, я тогда вообще не знал node js, а сейчас уже смело могу исправить ошибку.

**Comment by AdvTechnoKing** [comment]
Просто сейчас сижу на асинхроннике)

**Comment by Naltox** [comment]
Пофиксил
