### ISSUE TITLE
При выполнении wall.get ответ false

### ISSUE THREAD

**Issue by cheesega** [Naltox/node-vk-sdk#12]
по какой-то причине не выходит сделать запрос.
 ```
Group.api('wall.get', {owner_id: '-183816027', domain: 'starcheebots'}, (data, error) => {
    console.log(data)
    if (error) {
       console.log('Ошибка выполнения метода', error)
    } else {
       console.log(data)
    }
  })
```
и выводит постоянно false. Почему?

**Comment by MrZillaGold** [comment]
Этот метод нельзя вызвать с ключом доступа сообщества.
https://vk.com/dev/wall.get
![Аннотация 2019-07-14 174748](https://user-images.githubusercontent.com/42776347/61180799-99908500-a65f-11e9-914b-5d5f7ea4463b.png)
