### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by dimensi** [Naltox/node-vk-sdk#9]
Скопировал example из доки и вставил в index.js. В итоге мне приходит пустой ответ `[]`.

**Comment by stels-cs** [comment]
Это нормально, когда в сообщество никто не написал

**Comment by AdvTechnoKing** [comment]
или же ничего не происходит

**Comment by dimensi** [comment]
Нет, решение на самом деле не работало, но я просто начал дергать один запрос и все. Всем, спасибо.
